"""'user_id_added'

Revision ID: 66e460cc994e
Revises: 041f0bfa88f1
Create Date: 2023-02-24 14:26:13.335677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e460cc994e'
down_revision = '041f0bfa88f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
