"""'another_channels_deleted'

Revision ID: 7c31b5d36104
Revises: bf16c3a52c62
Create Date: 2023-02-24 11:36:00.029980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c31b5d36104'
down_revision = 'bf16c3a52c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('another_channel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('another_channel',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"another_channel_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='another_channel_pkey')
    )
    # ### end Alembic commands ###
