"""'link_added'

Revision ID: a59afee7238b
Revises: 668edff7291e
Create Date: 2023-02-24 15:06:30.381347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59afee7238b'
down_revision = '668edff7291e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'link')
    # ### end Alembic commands ###
